sudo: false
language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
env:
  - SIMPHONY_VERSION=0.2.0
  - SIMPHONY_VERSION=master
matrix:
  allow_failures:
    - env: SIMPHONY_VERSION=master
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install git+https://github.com/simphony/simphony-common.git@${SIMPHONY_VERSION}#egg=simphony
  - python setup.py develop
script:
  - flake8 .
  - python -m unittest discover
